### ISSUE TITLE
iCtrl randomly poping up

### ISSUE THREAD

**Issue by Leo6Leo** [junhaoliao/iCtrl#14]
**Describe the bug**
The desktop page will show up suddenly and randomly. 
![CleanShot 2022-10-23 at 22 28 22@2x](https://user-images.githubusercontent.com/36619969/197436834-13dfdecf-2fa7-4375-b14f-ec24a1ab4ee4.png)

**Comment by junhaoliao** [comment]
It seems to be an issue about the loading mechanism. I am looking into this now. Hopefully I can provide a fix by the end of this week.

**Comment by junhaoliao** [comment]
Fixed in d1201a3cfbd2b280ee30705eb8011791cfd8d785
